displayName: Return Static Response
summary: Return a static response for a given HTTP request.
type: middleware
import: github.com/jamesmcroft/traefik-plugin-return-response
testData:
  lastModified: true
  response:
    - method: "OPTIONS"
      url_match: "^https://(.+)$"
      status_code: 200
